version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: ml_service
    # Иначе можно:
    # image: your-dockerhub-acc/ml-service:latest
    # если вы уже собрали и запушили образ
    ports:
      - "8000:8000"
      - "5002:5002"
    environment:
      # Параметры MinIO (S3):
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin123
      # Для DVC нужен endpoint:
      - DVC_REMOTE_URL=http://minio:9000/ml-bucket
      # Или используйте MLFLOW_S3_ENDPOINT_URL при работе с MLflow
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - MINIO_ENDPOINT=http://minio:9000
      # Прочие переменные
      - MINIO_URL=http://minio:9000
      - MINIO_BUCKET_NAME=ml-bucket
      # MLflow tracking URI (если поднимаем mlflow вместе или отдельно)
      - MLFLOW_TRACKING_URI=http://localhost:5002
      # ... при необходимости добавьте свои ключи и т.д.
    depends_on:
      - minio
    # Если планируете использовать dvc push/pull внутри контейнера,
    # нужно либо маунтить volume, либо хранить dvc-файлы в контейнере.
    volumes:
      - ./:/app  # Пример монтирования кода (не всегда нужно)
      # - some_dvc_cache_volume:/app/.dvc/cache  # Если хотите отдельный volume для кеша

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  minio_data:
#     external: false


